FROM python:3.7.9-buster

ARG SCRIPT_NAME
ADD $SCRIPT_NAME $SCRIPT_NAME
ADD database.py database.py
ADD requirements.txt requirements.txt

RUN pip install -r requirements.txt
ENV SCRIPT_NAME=$SCRIPT_NAME

ENV WARRANTY_SERVICE_URL=$WARRANTY_SERVICE_URL
ENV WAREHOUSE_SERVICE_URL=$WAREHOUSE_SERVICE_URL
ENV ORDER_SERVICE_URL=$ORDER_SERVICE_URL

CMD python $SCRIPT_NAME
